### ISSUE TITLE
geonetworkx for qualicharge project

### ISSUE THREAD

**Issue by loco-philippe** [Artelys/geonetworkx#12]
As part of the 'qualicharge' project led by the French Interministerial Directorate for Digital Services (Dinum), an application based on Networkx and processing geospatial data has been developed.

This is currently being upgraded using a geospatial layer of Networkx. A [GeoNetworkX package](https://github.com/loco-labs/geonetworkx) has therefore been created for this. 

We now discover that this GeoNetworx is very close to the original project and the question arises of the convergences between the two approaches.

Is it possible to discuss this subject (email address: philippe@loco-labs.io) ?

**Comment by Hyrae** [comment]
Discussed directly.
